FROM rust:1.80-slim-bookworm as build

# create a new empty shell project
RUN USER=root cargo new --bin auth-backend
WORKDIR /auth-backend

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
RUN cargo build --release
RUN rm src/*.rs

# copy your source tree
COPY ./src ./src
COPY ./migrations ./migrations

# build for release
RUN cargo build --release

# our final base
FROM debian:bookworm-slim

# copy the build artifact from the build stage
COPY --from=build /auth-backend/target/release/auth-backend .

EXPOSE 8080

# set the startup command to run your binary
CMD ["./auth-backend"]